@startuml
object You
object "Redis" as RedisA
object "Redis" as RedisB
object RedisZ {
  urls = "a,b"
  pool_size = 2
}
object Diagnoser
object Server
object ETS
object Shards
object ShardsStarter
object "Shard" as ShardA {
  url = "a"
  pool_size = 2
}
object "Shard" as ShardB {
  url = "b"
  pool_size = 2
}
object "Pool" as PoolA {
  url = "a"
  pool_size = 2
}
object "PoolStarter" as PoolStarterA
object "Pool" as PoolB {
  url = "b"
  pool_size = 2
}
object "PoolStarter" as PoolStarterB
Object "Redix" as RedixA1 {
  url = "a"
}
Object "Redix" as RedixA2 {
  url = "a"
}
Object "Redix" as RedixB1 {
  url = "b"
}
Object "Redix" as RedixB2 {
  url = "b"
}

RedisZ <|-- Diagnoser
RedisZ <|-- Server
Server <|-- ETS
ETS <|.. You : read
RedisZ <|-- Shards
RedisZ <|-- ShardsStarter
Shards <|.. ShardsStarter
Shards <|-- ShardA
Shards <|-- ShardB
ShardA <|-- PoolA
ShardA <|-- PoolStarterA
PoolA <|.. PoolStarterA
ShardB <|-- PoolB
ShardB <|-- PoolStarterB
PoolB <|.. PoolStarterB
PoolA <|-- RedixA1
PoolA <|-- RedixA2
PoolB <|-- RedixB1
PoolB <|-- RedixB2
RedisA <|.. RedixA1 : pipeline
RedisA <|.. RedixA2 : pipeline
RedisB <|.. RedixB1 : pipeline
RedisB <|.. RedixB2 : pipeline
@enduml
